# Generated by Django 4.1.2 on 2022-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image1', models.FilePathField(default=None, path='/img')),
                ('image2', models.FilePathField(default=None, path='/img')),
                ('image3', models.FilePathField(default=None, path='/img')),
            ],
        ),
    ]
